version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  ch1:
    build:
      context: .
      dockerfile: Dockerfile.ch1
    depends_on:
      - zookeeper
    ports:
      - 8813:8123
      - 9011:9000
    volumes:
      - "/clickhouse-cluster-data/volume1:/var/lib/clickhouse"
  ch2:
    build:
      context: .
      dockerfile: Dockerfile.ch2
    depends_on:
      - zookeeper
    ports:
      - 8814:8123
      - 9012:9000
    volumes:
      - "/clickhouse-cluster-data/volume2:/var/lib/clickhouse"
  ch3:
    build:
      context: .
      dockerfile: Dockerfile.ch3
    depends_on:
      - zookeeper
    ports:
      - 8815:8123
      - 9013:9000
    volumes:
      - "/clickhouse-cluster-data/volume3:/var/lib/clickhouse"
