version: "3.8"
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  ch1:
    build:
      context: .
      dockerfile: Dockerfile.ch1
    depends_on:
      - zookeeper
    ports:
      - 8811:8123
      - 9011:9000
    volumes:
      - "/home/ttg/clickhouse-cluster/data/volume1:/var/lib/clickhouse"
  ch2:
    build:
      context: .
      dockerfile: Dockerfile.ch2
    depends_on:
      - zookeeper
    ports:
      - 8812:8123
      - 9012:9000
    volumes:
      - "/home/ttg/clickhouse-cluster/data/volume2:/var/lib/clickhouse"
  ch3:
    build:
      context: .
      dockerfile: Dockerfile.ch3
    depends_on:
      - zookeeper
    ports:
      - 8813:8123
      - 9013:9000
    volumes:
      - "/home/ttg/clickhouse-cluster/data/volume3:/var/lib/clickhouse"
